# Generated by Django 4.1.3 on 2022-11-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Democartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/img/banner.png', upload_to='product'),
        ),
    ]
